        !COMPILER-GENERATED INTERFACE MODULE: Thu May 30 22:36:42 2013
        MODULE INFLUENCE_COEFFICIENT__genmod
          INTERFACE 
            SUBROUTINE INFLUENCE_COEFFICIENT
            END SUBROUTINE INFLUENCE_COEFFICIENT
          END INTERFACE 
        END MODULE INFLUENCE_COEFFICIENT__genmod
