        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 13 15:08:00 2013
        MODULE INFLUENCE_COEFFICIENT__genmod
          INTERFACE 
            SUBROUTINE INFLUENCE_COEFFICIENT
            END SUBROUTINE INFLUENCE_COEFFICIENT
          END INTERFACE 
        END MODULE INFLUENCE_COEFFICIENT__genmod
