        !COMPILER-GENERATED INTERFACE MODULE: Fri Jun 14 08:51:13 2013
        MODULE INFLUENCE_COEFFICIENT__genmod
          INTERFACE 
            SUBROUTINE INFLUENCE_COEFFICIENT
            END SUBROUTINE INFLUENCE_COEFFICIENT
          END INTERFACE 
        END MODULE INFLUENCE_COEFFICIENT__genmod
