        !COMPILER-GENERATED INTERFACE MODULE: Fri Jun 14 09:16:52 2013
        MODULE INITIAL__genmod
          INTERFACE 
            SUBROUTINE INITIAL
            END SUBROUTINE INITIAL
          END INTERFACE 
        END MODULE INITIAL__genmod
