        !COMPILER-GENERATED INTERFACE MODULE: Wed May 29 08:45:17 2013
        MODULE CHECK_CONVERGENCE__genmod
          INTERFACE 
            SUBROUTINE CHECK_CONVERGENCE
            END SUBROUTINE CHECK_CONVERGENCE
          END INTERFACE 
        END MODULE CHECK_CONVERGENCE__genmod
