        !COMPILER-GENERATED INTERFACE MODULE: Wed May 29 08:45:17 2013
        MODULE INFLUENCE_COEFFICIENT__genmod
          INTERFACE 
            SUBROUTINE INFLUENCE_COEFFICIENT
            END SUBROUTINE INFLUENCE_COEFFICIENT
          END INTERFACE 
        END MODULE INFLUENCE_COEFFICIENT__genmod
