        !COMPILER-GENERATED INTERFACE MODULE: Thu May 30 14:51:09 2013
        MODULE INITIAL__genmod
          INTERFACE 
            SUBROUTINE INITIAL
            END SUBROUTINE INITIAL
          END INTERFACE 
        END MODULE INITIAL__genmod
