        !COMPILER-GENERATED INTERFACE MODULE: Wed May 29 08:45:17 2013
        MODULE OUTPUT__genmod
          INTERFACE 
            SUBROUTINE OUTPUT
            END SUBROUTINE OUTPUT
          END INTERFACE 
        END MODULE OUTPUT__genmod
