        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 22 19:56:25 2013
        MODULE BC_GHOSTCELL_VALUE__genmod
          INTERFACE 
            SUBROUTINE BC_GHOSTCELL_VALUE
            END SUBROUTINE BC_GHOSTCELL_VALUE
          END INTERFACE 
        END MODULE BC_GHOSTCELL_VALUE__genmod
