        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 22 19:56:23 2013
        MODULE INVISCID_FLUXES_LAX__genmod
          INTERFACE 
            SUBROUTINE INVISCID_FLUXES_LAX
            END SUBROUTINE INVISCID_FLUXES_LAX
          END INTERFACE 
        END MODULE INVISCID_FLUXES_LAX__genmod
