        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 13 08:16:32 2013
        MODULE CHECK_CONVERGENCE__genmod
          INTERFACE 
            SUBROUTINE CHECK_CONVERGENCE
            END SUBROUTINE CHECK_CONVERGENCE
          END INTERFACE 
        END MODULE CHECK_CONVERGENCE__genmod
