        !COMPILER-GENERATED INTERFACE MODULE: Sun Jun 19 23:01:42 2016
        MODULE BC_GHOSTCELL_VALUE__genmod
          INTERFACE 
            SUBROUTINE BC_GHOSTCELL_VALUE
            END SUBROUTINE BC_GHOSTCELL_VALUE
          END INTERFACE 
        END MODULE BC_GHOSTCELL_VALUE__genmod
