        !COMPILER-GENERATED INTERFACE MODULE: Sun Jun 19 23:01:42 2016
        MODULE OUTPUTUNS__genmod
          INTERFACE 
            SUBROUTINE OUTPUTUNS
            END SUBROUTINE OUTPUTUNS
          END INTERFACE 
        END MODULE OUTPUTUNS__genmod
