        !COMPILER-GENERATED INTERFACE MODULE: Sun Jun 19 23:01:42 2016
        MODULE RUNGE_KUTTA__genmod
          INTERFACE 
            SUBROUTINE RUNGE_KUTTA(NRK)
              INTEGER(KIND=4) :: NRK
            END SUBROUTINE RUNGE_KUTTA
          END INTERFACE 
        END MODULE RUNGE_KUTTA__genmod
