        !COMPILER-GENERATED INTERFACE MODULE: Sun Jun 19 23:55:38 2016
        MODULE SOLVER__genmod
          INTERFACE 
            SUBROUTINE SOLVER(NRK)
              INTEGER(KIND=4) :: NRK
            END SUBROUTINE SOLVER
          END INTERFACE 
        END MODULE SOLVER__genmod
