        !COMPILER-GENERATED INTERFACE MODULE: Sun Jun 19 23:01:42 2016
        MODULE STARTUP__genmod
          INTERFACE 
            SUBROUTINE STARTUP
            END SUBROUTINE STARTUP
          END INTERFACE 
        END MODULE STARTUP__genmod
