        !COMPILER-GENERATED INTERFACE MODULE: Sun Jun 19 23:01:42 2016
        MODULE UPDATE_VARIABLES__genmod
          INTERFACE 
            SUBROUTINE UPDATE_VARIABLES
            END SUBROUTINE UPDATE_VARIABLES
          END INTERFACE 
        END MODULE UPDATE_VARIABLES__genmod
