        !COMPILER-GENERATED INTERFACE MODULE: Sun Jun 19 23:01:42 2016
        MODULE VOLUME_STATIC__genmod
          INTERFACE 
            SUBROUTINE VOLUME_STATIC
            END SUBROUTINE VOLUME_STATIC
          END INTERFACE 
        END MODULE VOLUME_STATIC__genmod
