        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 13 22:14:05 2013
        MODULE INITIAL__genmod
          INTERFACE 
            SUBROUTINE INITIAL
            END SUBROUTINE INITIAL
          END INTERFACE 
        END MODULE INITIAL__genmod
