      PROGRAM CONTR
      INCLUDE 'HEAD' 
      DATA HEDU/4HU U /,HEDV/4HV V /,HEDP/4HP P /,HEDPP/4HP'P'/,
     1     HEDM/4HVIS /,HEDR/4HDENS/ 
C
CHAPTER  1  1  1  1  1  1  1  1  CONTROL INDICES  1  1  1  1  1  1  1  1
C
C---------SET IWRITE=.TRUE. ONLY FOR WRITING SOLN. ON DATA FILES
      IWRIT=.FALSE.
C---------SET IREAD=.TRUE. ONLY FOR READING INITIAL GUESS OF SOLN.
C---------     FROM DATA FILES
      IREAD=.FALSE.
C---------PROBLEM SELECTION
      INSG=.TRUE.
C---------DEPENDENT VARIABLE SELECTION 1
      INCALU=.TRUE.
      INCALV=.TRUE.
      INCALP=.TRUE.
	INCALK=.true.
	INCALD=.true.
      INCALC=.FALSE.
	INCALT=.true.
      INPROV=.true.
C
CHAPTER  2  2  2  2  2  2  2  2  GRID  2  2  2  2  2  2  2  2
C       
	CALL GRID
	CALL GEOME
C
CHAPTER  3  3  3  3  3  3  INPUTING DATA  3  3  3  3  3  3
C       
	IF(INSG) CALL INPUT
C
CHAPTER  4  4  4  4  4  4  INITIAL OPERATION  4  4  4  4  4  4
C       
	IF(INSG) CALL ZERO
C
CHAPTER  5  5  5  5  5  STARTING PREPARATIONS  5  5  5  5  5
C       
      IF(INSG) CALL START
	nfile=8
	OPEN(nfile,FILE='UOUT0')
	CALL PRINT(NI,NJ,IT,JT,XU,Y,U,'UUUU',nfile)
      close(NFILE)
	nfile=9
	open(nfile,file='VOUT0')
	CALL PRINT(NI,NJ,IT,JT,X,YV,V,'VVVV',nfile)
      CLOSE(NFILE)
	nfile=11
	open(nfile,file='POUT0')
      CALL PRINT(NI,NJ,IT,JT,X,Y,P,'PPPP',nfile)
	close(nfile)
	NFILE=12
	OPEN(NFILE,FILE='PPOUT0')
	CALL PRINT(NI,NJ,IT,JT,X,Y,PP,'P P ',nfile)
	CLOSE(NFILE)    
C
CHAPTER  6  6  6  6  6  6  ITERATION LOOP  6  6  6  6  6  6
C       
      MAXNIT=3000
	SOMAX=2.0e-4
      NITER=0
	IMON=20
	JMON=5
      NPR=1000
	open(10,file='eout')
      IF(INSG) CALL ITER(SOMAX,MAXNIT,SORCE,NITER,IMON,JMON,NPR)        
70    CONTINUE
	nfile=8
	OPEN(nfile,FILE='UOUT')
	CALL PRINT(NI,NJ,IT,JT,XU,Y,U,'UUUU',nfile)
      close(NFILE)
	nfile=9
	open(nfile,file='VOUT')
	CALL PRINT(NI,NJ,IT,JT,X,YV,V,'VVVV',nfile)
      CLOSE(NFILE)
	nfile=11
	open(nfile,file='POUT')
      CALL PRINT(NI,NJ,IT,JT,X,Y,P,'PPPP',nfile)
	close(nfile)
	NFILE=12
	OPEN(NFILE,FILE='PPOUT')
	CALL PRINT(NI,NJ,IT,JT,X,Y,PP,'P P ',nfile)
	CLOSE(NFILE)    
	NFILE=13
	OPEN(NFILE,FILE='TEOUT')
	CALL PRINT(NI,NJ,IT,JT,X,Y,TE,'TETE',nfile)
	CLOSE(NFILE)    
	NFILE=14
	OPEN(NFILE,FILE='EDOUT')
	CALL PRINT(NI,NJ,IT,JT,X,Y,ED,'EDED',nfile)
	CLOSE(NFILE)    
	NFILE=15
	OPEN(NFILE,FILE='VISOUT')
	CALL PRINT(NI,NJ,IT,JT,X,Y,VIS,'VISS',nfile)
	CLOSE(NFILE) 
	NFILE=16
	OPEN(NFILE,FILE='TOUT')
	CALL PRINT(NI,NJ,IT,JT,X,Y,T,'TTTT',nfile)
	CLOSE(NFILE)    
	NFILE=17
	OPEN(NFILE,FILE='O2OUT')
	CALL PRINT(NI,NJ,IT,JT,X,Y,YO2,'O2O2',nfile)
	CLOSE(NFILE)    
	NFILE=18
	OPEN(NFILE,FILE='O2OUT')
	CALL PRINT(NI,NJ,IT,JT,X,Y,YCH4,'CH4 ',nfile)
	CLOSE(NFILE)    
	NFILE=19
	OPEN(NFILE,FILE='O2OUT')
	CALL PRINT(NI,NJ,IT,JT,X,Y,YCO2,'CO2 ',nfile)
	CLOSE(NFILE)    
	NFILE=20
	OPEN(NFILE,FILE='H2OOUT')
	CALL PRINT(NI,NJ,IT,JT,X,Y,YH2O,'H2OH',nfile)
	CLOSE(NFILE)    
	NFILE=21
	OPEN(NFILE,FILE='DENOUT')
	CALL PRINT(NI,NJ,IT,JT,X,Y,DEN,'DEND',nfile)
	CLOSE(NFILE)    
	CALL OUTGT
      close(10)
	stop
	END