        !COMPILER-GENERATED INTERFACE MODULE: Wed May 18 16:20:18 2016
        MODULE INVISCID_FLUXES_LAX__genmod
          INTERFACE 
            SUBROUTINE INVISCID_FLUXES_LAX
            END SUBROUTINE INVISCID_FLUXES_LAX
          END INTERFACE 
        END MODULE INVISCID_FLUXES_LAX__genmod
