        !COMPILER-GENERATED INTERFACE MODULE: Wed May 18 19:20:37 2016
        MODULE STARTUP__genmod
          INTERFACE 
            SUBROUTINE STARTUP
            END SUBROUTINE STARTUP
          END INTERFACE 
        END MODULE STARTUP__genmod
