        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 22 19:56:23 2013
        MODULE INTERPOLATION_TO_INTERFACE__genmod
          INTERFACE 
            SUBROUTINE INTERPOLATION_TO_INTERFACE
            END SUBROUTINE INTERPOLATION_TO_INTERFACE
          END INTERFACE 
        END MODULE INTERPOLATION_TO_INTERFACE__genmod
