        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 22 19:56:24 2013
        MODULE OUTPUTUNS__genmod
          INTERFACE 
            SUBROUTINE OUTPUTUNS
            END SUBROUTINE OUTPUTUNS
          END INTERFACE 
        END MODULE OUTPUTUNS__genmod
