        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 22 19:56:23 2013
        MODULE RUNGE_KUTTA__genmod
          INTERFACE 
            SUBROUTINE RUNGE_KUTTA(NRK)
              INTEGER(KIND=4) :: NRK
            END SUBROUTINE RUNGE_KUTTA
          END INTERFACE 
        END MODULE RUNGE_KUTTA__genmod
