        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 22 19:56:22 2013
        MODULE STARTUP__genmod
          INTERFACE 
            SUBROUTINE STARTUP
            END SUBROUTINE STARTUP
          END INTERFACE 
        END MODULE STARTUP__genmod
