        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 22 19:56:23 2013
        MODULE UPDATE_VARIABLES__genmod
          INTERFACE 
            SUBROUTINE UPDATE_VARIABLES
            END SUBROUTINE UPDATE_VARIABLES
          END INTERFACE 
        END MODULE UPDATE_VARIABLES__genmod
