        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 22 19:56:23 2013
        MODULE VOLUME_STATIC__genmod
          INTERFACE 
            SUBROUTINE VOLUME_STATIC
            END SUBROUTINE VOLUME_STATIC
          END INTERFACE 
        END MODULE VOLUME_STATIC__genmod
