        !COMPILER-GENERATED INTERFACE MODULE: Fri May 31 15:56:43 2013
        MODULE INITIAL__genmod
          INTERFACE 
            SUBROUTINE INITIAL
            END SUBROUTINE INITIAL
          END INTERFACE 
        END MODULE INITIAL__genmod
