        !COMPILER-GENERATED INTERFACE MODULE: Fri May 31 13:53:24 2013
        MODULE OUTPUT__genmod
          INTERFACE 
            SUBROUTINE OUTPUT
            END SUBROUTINE OUTPUT
          END INTERFACE 
        END MODULE OUTPUT__genmod
