        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 23 20:06:10 2016
        MODULE AREA__genmod
          INTERFACE 
            SUBROUTINE AREA
            END SUBROUTINE AREA
          END INTERFACE 
        END MODULE AREA__genmod
