        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 21 17:02:00 2016
        MODULE AREA__genmod
          INTERFACE 
            SUBROUTINE AREA
            END SUBROUTINE AREA
          END INTERFACE 
        END MODULE AREA__genmod
