        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 23 20:06:11 2016
        MODULE BC_GHOSTCELL_VALUE__genmod
          INTERFACE 
            SUBROUTINE BC_GHOSTCELL_VALUE
            END SUBROUTINE BC_GHOSTCELL_VALUE
          END INTERFACE 
        END MODULE BC_GHOSTCELL_VALUE__genmod
