        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 21 17:02:00 2016
        MODULE BC_GHOSTCELL_VALUE__genmod
          INTERFACE 
            SUBROUTINE BC_GHOSTCELL_VALUE
            END SUBROUTINE BC_GHOSTCELL_VALUE
          END INTERFACE 
        END MODULE BC_GHOSTCELL_VALUE__genmod
