        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 20 17:36:08 2016
        MODULE INVISCID_FLUXES_LAX__genmod
          INTERFACE 
            SUBROUTINE INVISCID_FLUXES_LAX
            END SUBROUTINE INVISCID_FLUXES_LAX
          END INTERFACE 
        END MODULE INVISCID_FLUXES_LAX__genmod
