        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 21 17:02:00 2016
        MODULE INVISCID_FLUXES_LAX__genmod
          INTERFACE 
            SUBROUTINE INVISCID_FLUXES_LAX
            END SUBROUTINE INVISCID_FLUXES_LAX
          END INTERFACE 
        END MODULE INVISCID_FLUXES_LAX__genmod
