        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 23 20:06:10 2016
        MODULE INVISCID_FLUXES_LAX__genmod
          INTERFACE 
            SUBROUTINE INVISCID_FLUXES_LAX
            END SUBROUTINE INVISCID_FLUXES_LAX
          END INTERFACE 
        END MODULE INVISCID_FLUXES_LAX__genmod
