        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 21 17:02:00 2016
        MODULE OUTPUTUNS__genmod
          INTERFACE 
            SUBROUTINE OUTPUTUNS
            END SUBROUTINE OUTPUTUNS
          END INTERFACE 
        END MODULE OUTPUTUNS__genmod
