        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 20 17:36:08 2016
        MODULE OUTPUT__genmod
          INTERFACE 
            SUBROUTINE OUTPUT
            END SUBROUTINE OUTPUT
          END INTERFACE 
        END MODULE OUTPUT__genmod
