        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 20 17:36:08 2016
        MODULE OUTPUTUNS__genmod
          INTERFACE 
            SUBROUTINE OUTPUTUNS
            END SUBROUTINE OUTPUTUNS
          END INTERFACE 
        END MODULE OUTPUTUNS__genmod
