        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 23 20:06:10 2016
        MODULE OUTPUTUNS__genmod
          INTERFACE 
            SUBROUTINE OUTPUTUNS
            END SUBROUTINE OUTPUTUNS
          END INTERFACE 
        END MODULE OUTPUTUNS__genmod
