        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 21 17:02:00 2016
        MODULE RUNGE_KUTTA__genmod
          INTERFACE 
            SUBROUTINE RUNGE_KUTTA(NRK)
              INTEGER(KIND=4) :: NRK
            END SUBROUTINE RUNGE_KUTTA
          END INTERFACE 
        END MODULE RUNGE_KUTTA__genmod
