        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 20 17:36:08 2016
        MODULE RUNGE_KUTTA__genmod
          INTERFACE 
            SUBROUTINE RUNGE_KUTTA(NRK)
              INTEGER(KIND=4) :: NRK
            END SUBROUTINE RUNGE_KUTTA
          END INTERFACE 
        END MODULE RUNGE_KUTTA__genmod
