        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 21 17:02:00 2016
        MODULE SOLVER__genmod
          INTERFACE 
            SUBROUTINE SOLVER(NRK)
              INTEGER(KIND=4) :: NRK
            END SUBROUTINE SOLVER
          END INTERFACE 
        END MODULE SOLVER__genmod
