        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 20 17:36:08 2016
        MODULE STARTUP__genmod
          INTERFACE 
            SUBROUTINE STARTUP
            END SUBROUTINE STARTUP
          END INTERFACE 
        END MODULE STARTUP__genmod
