        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 21 17:02:00 2016
        MODULE STARTUP__genmod
          INTERFACE 
            SUBROUTINE STARTUP
            END SUBROUTINE STARTUP
          END INTERFACE 
        END MODULE STARTUP__genmod
