        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 23 20:06:10 2016
        MODULE STARTUP__genmod
          INTERFACE 
            SUBROUTINE STARTUP
            END SUBROUTINE STARTUP
          END INTERFACE 
        END MODULE STARTUP__genmod
