        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 20 17:36:08 2016
        MODULE UPDATE_VARIABLES__genmod
          INTERFACE 
            SUBROUTINE UPDATE_VARIABLES
            END SUBROUTINE UPDATE_VARIABLES
          END INTERFACE 
        END MODULE UPDATE_VARIABLES__genmod
