        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 21 17:02:00 2016
        MODULE UPDATE_VARIABLES__genmod
          INTERFACE 
            SUBROUTINE UPDATE_VARIABLES
            END SUBROUTINE UPDATE_VARIABLES
          END INTERFACE 
        END MODULE UPDATE_VARIABLES__genmod
