        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 23 20:06:10 2016
        MODULE UPDATE_VARIABLES__genmod
          INTERFACE 
            SUBROUTINE UPDATE_VARIABLES
            END SUBROUTINE UPDATE_VARIABLES
          END INTERFACE 
        END MODULE UPDATE_VARIABLES__genmod
