        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 23 20:06:10 2016
        MODULE VOLUME_STATIC__genmod
          INTERFACE 
            SUBROUTINE VOLUME_STATIC
            END SUBROUTINE VOLUME_STATIC
          END INTERFACE 
        END MODULE VOLUME_STATIC__genmod
