        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 21 17:02:00 2016
        MODULE VOLUME_STATIC__genmod
          INTERFACE 
            SUBROUTINE VOLUME_STATIC
            END SUBROUTINE VOLUME_STATIC
          END INTERFACE 
        END MODULE VOLUME_STATIC__genmod
