	subroutine flowrate_modifying
	INCLUDE 'HEAD'
	DIMENSION DELTP(IX)
	DO 710 I=1,NI
	DELTP(I)=0.0
710   CONTINUE
	DO 22 I=3,NIM1
	FLOW=0.0
	ARDENT=0.0
	AREA=0.0
	DO 21 J=2,NJM1
	AREAW=SSN(J)*RCV(J)
	AREA=AREA+AREAW
	ARDENT=ARDENT+(DEN(I,J)*XICUE(I)+DEN(I-1,J)*XICUW(I))*AREAW
      FLOW=FLOW+(DEN(I,J)*XICUE(I)+DEN(I-1,J)*XICUW(I))*U(I,J)
     1	*AREAW
21    CONTINUE	
      DELTU=(FLOWIN-FLOW)/(ARDENT+1E-30)
	DELTP(I)=2.0*FLOWIN*DELTU/(AREA+1E-30)
	DO 25 J=1,NJM1
	U(I,J)=U(I,J)+DELTU
25    CONTINUE
22    CONTINUE	
      DO 510 I=NIM1,2,-1
	DELTP(I)=DELTP(I)+DELTP(I+1)
510   CONTINUE
      DO 520 I=2,NIM1
	DELTP(I)=DELTP(I)-DELTP(IPREF)
520   continue	
      DO 610 J=2,NJM1
      DO 610 I=2,NIM1
	P(I,J)=P(I,J)+DELTP(I)
610   CONTINUE
      RETURN 
	END