	SUBROUTINE OUTGT
	INCLUDE 'HEAD'
	DIMENSION UTEMP(350,20),VTEMP(350,20)   
      DO J=1,NJ
	UTEMP(1,J)=U(1,J)
	UTEMP(NI,J)=U(NI,J)
	END DO
	DO J=1,NJ
	DO I=2,NIM1
	UTEMP(I,J)=U(I,J)+(U(I+1,J)-U(I,J))/(XU(I+1)-XU(I))*
	1           (X(I)-XU(I))
	END DO
	END DO
	DO I=1,NI
	VTEMP(I,1)=V(I,1)
	VTEMP(I,NJ)=V(I,NJ)
	END DO
	DO I=1,NI
	DO J=2,NJM1
	VTEMP(I,J)=V(I,J)+(V(I,J+1)-V(I,J))/(YV(J+1)-YV(J))*
	1           (Y(J)-YV(J))
	END DO
	END DO
	OPEN(150,FILE='RESULT.DAT')
	WRITE(150,*)'TITLE="RESULT.DAT"'
	WRITE(150,*)'VARIABLES="X","Y","U","V","C","P","PP","TE","ED","T",
	1"CH4","O2","CO2","H2O"'           
	WRITE(150,1115)NJ,NI
1115  FORMAT(' ZONE J=',I3,' ,I=',I3)
	DO J=NJ,1,-1
	DO I=1,NI,1
	WRITE(150,1120)X(I),Y(J),U(I,J),V(I,J),C(I,J),P(I,J),PP(I,J),
     1TE(I,J),ED(I,J),T(I,J),YCH4(I,J),YO2(I,J),YCO2(I,J),YH2O(I,J)
	END DO 
	END DO
	CLOSE(150)
1120  FORMAT(1X,15(E11.3,1X))
	RETURN
      END