      SUBROUTINE ITER(SOMAX,MAXIE,SORCE,NITER,IMON,JMON,NPR)
	INCLUDE 'HEAD'
	WRITE(*,50)
10    NITER=NITER+1
      IF(NPRINT.LT.NITER)NPRINT=NPR+NITER 
C---------UPDATE MAIN DEPENDENT VARIABLES                               
      IF(INCALU) CALL CALCU    
      IF(INCALV) CALL CALCV
      IF(INCALP) CALL CALCP
	IF(INCALP) CALL FLOWRATE_MODIFYING 
C      IF(INCALC) CALL CALCC 
	IF(INCALK) CALL CALCTE 
      IF(INCALD) CALL CALCED
      IF(INCALT) CALL CALCY(1)
      IF(INCALT) CALL CALCY(2)
      IF(INCALT) CALL CALCY(3)
      IF(INCALT) CALL CALCY(4)
      IF(INCALT) CALL CALCY(5)
C---------UPDATE FLUID  PROPERITIES                                     
      IF(INPROV) CALL PROPS
C---------INTERMEDIATE OUTPUT
      RESORM=RESORM/FLOWIN                                              
      RESORU=RESORU/XMONIN                                              
      RESORV=RESORV/XMONIN 
	RESORT=RESORT/TMONIN
      RESORK=RESORK/(.5*FLOWIN*UMEAN*UMEAN)     
	IF(NITER.NE.NPRINT)GOTO 20
	nfile=8
	OPEN(nfile,FILE='OUT')
	CALL PRINT(NI,NJ,IT,JT,XU,Y,U,'UUUU',nfile)
	CALL PRINT(NI,NJ,IT,JT,X,YV,V,'VVVV',nfile)
	CALL PRINT(NI,NJ,IT,JT,X,Y,P,'PPPP',nfile)
	CALL PRINT(NI,NJ,IT,JT,X,Y,PP,'P P ',nfile)
	CALL PRINT(NI,NJ,IT,JT,X,Y,DEN,'DEN ',nfile)
	CALL PRINT(NI,NJ,IT,JT,X,Y,TE,'TETE',nfile)
	CALL PRINT(NI,NJ,IT,JT,X,Y,ED,'EDED',nfile)
	CLOSE(8)
20    CONTINUE
      WRITE(*,60)NITER,RESORU,RESORV,RESORM,RESORC,RESORK,RESORE,
     1           RESORT,RESCH4,RESOO2,RESCO2,RESH2O,U(IMON,JMON),
     *V(IMON,JMON),P(IMON,JMON),TE(IMON,JMON),ED(IMON,JMON)
C---------TERMINATION TESTS                                             
      SORCE=AMAX1(RESORM,RESORU,RESORV,RESORK,RESORT)
      IF(SORCE.LE.SOMAX)then
	write(*,70)
	GOTO 40
	end if
      IF(NITER.GE.MAXIE)then
	write(*,80)
	GOTO 30
	end if
      IF(SORCE.GT.SOMAX.AND.NITER.LT.MAXIE) GOTO 10
30	IF(NITER.GE.150.AND.SORCE.GE.3.0) WRITE(*,90)
40    CONTINUE
      RETURN
50    FORMAT(1X,'Iter Number, Absolute Residual Source Sums',
     1/2x,14H  NO      UMON,8X,'VMON',8X,'MASS')
60    FORMAT(2X,I4,1x,16(E11.4,1x))
70    FORMAT(15X,'迭代已经收敛')
80    FORMAT(15X,'达到最大迭代次数前没有收敛')
90    FORMAT(15X,'求解过程不收敛')
      END