        !COMPILER-GENERATED INTERFACE MODULE: Thu May 30 22:10:57 2013
        MODULE CHECK_CONVERGENCE__genmod
          INTERFACE 
            SUBROUTINE CHECK_CONVERGENCE
            END SUBROUTINE CHECK_CONVERGENCE
          END INTERFACE 
        END MODULE CHECK_CONVERGENCE__genmod
