        !COMPILER-GENERATED INTERFACE MODULE: Thu May 30 22:10:56 2013
        MODULE INITIAL__genmod
          INTERFACE 
            SUBROUTINE INITIAL
            END SUBROUTINE INITIAL
          END INTERFACE 
        END MODULE INITIAL__genmod
