        !COMPILER-GENERATED INTERFACE MODULE: Wed May 18 16:20:17 2016
        MODULE BC_GHOSTCELL_VALUE__genmod
          INTERFACE 
            SUBROUTINE BC_GHOSTCELL_VALUE
            END SUBROUTINE BC_GHOSTCELL_VALUE
          END INTERFACE 
        END MODULE BC_GHOSTCELL_VALUE__genmod
