        !COMPILER-GENERATED INTERFACE MODULE: Wed May 18 16:20:18 2016
        MODULE RUNGE_KUTTA__genmod
          INTERFACE 
            SUBROUTINE RUNGE_KUTTA(NRK)
              INTEGER(KIND=4) :: NRK
            END SUBROUTINE RUNGE_KUTTA
          END INTERFACE 
        END MODULE RUNGE_KUTTA__genmod
