        !COMPILER-GENERATED INTERFACE MODULE: Wed May 18 16:20:16 2016
        MODULE VOLUME_STATIC__genmod
          INTERFACE 
            SUBROUTINE VOLUME_STATIC
            END SUBROUTINE VOLUME_STATIC
          END INTERFACE 
        END MODULE VOLUME_STATIC__genmod
